Category info edit refactoring
aelve/guide pull request #275
Opened 2019-03-29 11:23 UTC by Gigiman

Minor fixes with more declarative naming and imports similar to the code style used in project

2019-04-02 08:58 UTC, avele requested changes

2019-04-02 08:58 UTC, avele commented on front/client/components/CategoryInfoEdit.vue
> +  categoryStage: object = {}
Why rename? At backend it's still called status.

2019-04-25 15:18 UTC, neongreen commented
@avele what should be done about this PR? Can you fix it, or should it just be closed?

2019-05-18 11:18 UTC, avele approved these changes

2019-05-18 13:47 UTC, merged