Add target _blank
aelve/guide pull request #398
Opened 2019-09-26 09:15 UTC by willbasky

2019-09-26 09:18 UTC, willbasky commented
___
*[back/src/Guide/Markdown.hs, line 193 at r1](https://reviewable.io/reviews/aelve/guide/398#-LpgqyYn-ROnBb330umI:-LpgqyYo2RVMmpRZmvU8:b-s1p1h9) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L193)):*
> ```Haskell
> 
> -- | Convert LINK to HTML_INLINE with 'target="blank"' attribute added.
> linkToHtmlInline :: MD.Node -> MD.Node
> ```

Not sure it is enough pattern matching or there are other cases.


<!-- Sent from Reviewable.io -->

2019-09-28 13:09 UTC, neongreen requested changes
> *[Reviewable](https://reviewable.io/reviews/aelve/guide/398)* status: 0 of 2 files reviewed, 6 unresolved discussions (waiting on @neongreen and @willbasky)

___
*[back/src/Guide/Markdown.hs, line 192 at r1](https://reviewable.io/reviews/aelve/guide/398#-Lprz3Z_1-u5u71MzW4T:-Lprz3Z_1-u5u71MzW4U:bo71nvu) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L192)):*
> ```Haskell
>       CODE_BLOCK _ xs   -> [MD.Node Nothing (CODE xs) []]
> 
> -- | Convert LINK to HTML_INLINE with 'target="blank"' attribute added.
> ```

The comment should also say why we are doing it.
___
*[back/src/Guide/Markdown.hs, line 193 at r1](https://reviewable.io/reviews/aelve/guide/398#-LpgqyYn-ROnBb330umI:-LprwEUiAob5chdDrOrt:bqqiga0) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L193)):*
<details><summary><i>Previously, willbasky (Vladislav Sabanov) wrote…</i></summary><blockquote>

Not sure it is enough pattern matching or there are other cases.
</blockquote></details>

I think there are no other cases.
___
*[back/src/Guide/Markdown.hs, line 193 at r1](https://reviewable.io/reviews/aelve/guide/398#-Lprz8B962pl10em2dXV:-Lprz8B962pl10em2dXW:b-1zwveo) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L193)):*
> ```Haskell
> 
> -- | Convert LINK to HTML_INLINE with 'target="blank"' attribute added.
> linkToHtmlInline :: MD.Node -> MD.Node
> ```

`linkToHtmlInline` is not a good name – it might seem like it doesn't actually change anything. How about `addTargetBlank`?
___
*[back/src/Guide/Markdown.hs, line 194 at r1](https://reviewable.io/reviews/aelve/guide/398#-LprxtPm6-V8qcGTEC4s:-LprxtPm6-V8qcGTEC4t:bj2oagr) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L194)):*
> ```Haskell
> -- | Convert LINK to HTML_INLINE with 'target="blank"' attribute added.
> linkToHtmlInline :: MD.Node -> MD.Node
> linkToHtmlInline (MD.Node pos (LINK url _) ns) =
> ```

You shouldn't ignore the second field in `LINK`.

```
linkToHtmlInline (MD.Node pos (LINK url title) ns) =
```

It's used for [link titles](https://spec.commonmark.org/0.28/#example-459). The insides of the link are the contents, not a "title".
___
*[back/src/Guide/Markdown.hs, line 198 at r1](https://reviewable.io/reviews/aelve/guide/398#-LprwW4b4T0AtQrXmusM:-LprwW4b4T0AtQrXmusN:bo235g6) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/src/Guide/Markdown.hs#L198)):*
> ```Haskell
>   where
>     blankLink = toText $
>       renderText $ a_ [href_ url, target_ "_blank"] $ title $ head ns
> ```

Wait, what's happening here? Why `head ns`? The link might have several elements inside it, not just a single piece of text. It can be, for instance, `[foo *bar*](https://some.link)`.

You need to render the insides of the link with `renderMD`:

```haskell
a_ ([href url, target_ "_blank"] ++ [title_ title | title /= ""]) $ 
  toHtmlRaw $ renderMD ns
```
___
*[back/tests/MarkdownSpec.hs, line 43 at r1](https://reviewable.io/reviews/aelve/guide/398#-LprvusXA7AuuB8OKdvE:-LprvusXA7AuuB8OKdvF:b-srrqkf) ([raw file](https://github.com/aelve/guide/blob/19f34548a893ae50306933ac110f18d0f2ba1072/back/tests/MarkdownSpec.hs#L43)):*
> ```Haskell
>       let s = "[text](@hk)"
>       let html = snd (convert s)
>       let l = "<a href=\"https://hackage.haskell.org/package/text\" target=\"_blank\">text</a>"
> ```

There should also be a specific test for links and how they get `target="blank"` attached to them.


<!-- Sent from Reviewable.io -->

2019-09-28 13:10 UTC, neongreen reviewed
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/aelve/guide/398)* status: all files reviewed, 6 unresolved discussions (waiting on @willbasky)



<!-- Sent from Reviewable.io -->

2019-10-30 13:16 UTC, neongreen requested changes
> Reviewed 1 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/aelve/guide/398)* status: 1 of 2 files reviewed, 3 unresolved discussions (waiting on @neongreen and @willbasky)

___
*[back/src/Guide/Markdown.hs, line 115 at r2](https://reviewable.io/reviews/aelve/guide/398#-LqDRqxx3-UcTeNbB04M:-LqDRqxx3-UcTeNbB04N:b33kjzm) ([raw file](https://github.com/aelve/guide/blob/4e28e6407310e3d3e949eb67e072693e7942a344/back/src/Guide/Markdown.hs#L115)):*
> ```Haskell
>   STRONG            -> True
>   LINK _ _          -> True
>   IMAGE _ _         -> True
> ```

Huh. Okay, that was a bug, yeah.


<!-- Sent from Reviewable.io -->

2019-10-30 13:19 UTC, neongreen commented on back/src/Guide/Markdown.hs
> +-- | Convert LINK to HTML_INLINE with 'target="_blank"' attribute added.
```suggestion
-- | Convert 'LINK' to 'HTML_INLINE' with @target="_blank"@ attribute added.
```

2019-10-30 13:19 UTC, neongreen commented on back/src/Guide/Markdown.hs
> +-- It is necessary that the rendered html page be opened in a new tab.
```suggestion
-- It will cause the link to be opened in a new tab, which is the behavior
-- we want for links in the content.
```

2019-10-30 13:20 UTC, neongreen approved these changes

2019-10-30 13:21 UTC, neongreen commented
Please merge when my suggestions are committed.

2019-10-30 13:21 UTC, merged

2019-10-30 13:22 UTC, neongreen commented
Oops, it got merged by itself. I will apply the suggestions to `develop`.